name: Playwright C# Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Restore .NET local tools
      run: dotnet tool restore

    - name: Build the solution
      run: dotnet build --configuration Release

    - name: Install Playwright Browsers
      run: dotnet playwright install

    - name: Run Playwright Tests
      run: dotnet test --configuration Release --no-build --verbosity normal
